version: "3"

services:
  postgres:
    image: "postgres:9.5"
    volumes:
      - postgres:/var/lib/postgresql/data

  webpacker:
    build: .
    env_file:
      - '.env.docker'
    command: ./bin/webpack-dev-server --inline true 
    volumes:
      - .:/onebitflix
      - gems:/gems
    ports:
      - '3035:3035'

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitflix
      - gems:/gems
 

volumes:
  postgres:
  gems:
  webpacker:  